name: 'Chromatic Publish'

# Event for the workflow
on:
    push:
        branches:
            - 'feature/storybook'

# List of jobs
jobs:
    chromatic-deployment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Install dependecies
              run: yarn
              # Adds Chromatic as a step in the workflow
            - name: Publish to Chromatic
              uses: chromaui/action@v1
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  exitZeroOnChanges: true # Option to prevent the workflow from failing
